Expname: sv_${Model.vit}_gtdepth-pretrained_left-pattern_patenc-${Model.pat_enc_type}_prompt-${Model.prompting_net_type}_zeromodule_resize

Dataset:
  split: train
  batch_size: 4
  num_workers: 2
  data_root: # PATH TO NSL DATA_ROOT
  cleaned: True
  decomp: False
  ftype: local
  gray: True
  parameters: True
  patternname: null


Model:
  pretrained_path: zoo/ckpts/sv_vitb_gtdepth-prompt_max-norm_metric-pretrained.pt
  override_vit_pretrained: null
  # vit module
  vit: vitb
  # dpt head
  prompt_feat_dim: 1
  prompt_feat_proj_type: cnn
  use_zero_module: True
  do_reassemble: True
  # config for PatternPrompt
  prompting_net_type: RaftDepth
  pat_encoder_dim: 1
  pat_prompt_shared_transformer: True
  pat_enc_type: none
  pat_enc_extra_cfg:

  pat_epi_trans_cfg:
    depth_type: ${Train.depth_type}
    iters: 32
    d_in: [128,128,128]
    pretrained: zoo/ckpts/raft_left-patt_ep101.pth # zoo/ckpts/raft_left_patt_latest.pth
    context_norm: batch
    n_downsample: 2
    n_gru_layers: 3
    corr_levels: 4
    corr_radius: 4
    corr_implementation: reg
    shared_backbone: False
    mixed_precision: True
    slow_fast_gru: False
    freeze_bn: True
  prompt_input_modal: left_pattern
  lcn_wnd_size: 9
  max_depth: 10.0

Train:
  n_gpus: 4
  n_epoches: 10
  n_epoches_per_ckpt: 1
  n_steps_per_vis: 500
  n_steps_per_epoch: 10000
  seed: 42
  inp_size: 518
  min_depth: 0.1
  max_depth: ${Model.max_depth}
  near: ${Train.min_depth}
  far: ${Model.max_depth}
  depth_type: norm_depth
  grad_norm: 10

  fwd_kwargs:
    depth_type: ${Train.depth_type}
    lcn: False
    get_extra: False

  aug:
    - Transpose:  # must
    - RectifyPatterns:
        normalized_intri: False
    - Resize:
        target_h: ${Train.inp_size}
        target_w: 924
        resize_depth: True
        ori_w: 1280
        ori_h: 720
        normalized_intri: False
        channel_last: False
        mode: bilinear
    - RandomCrop:
        target_h: ${Train.inp_size}
        target_w: ${Train.inp_size}
        normalized_intri: False
        channel_last: False
        to_normalize_intri: False
    - RandomGammaCorrection:
        gamma: [0.7, 1.3]

  optimizer:
    type: AdamW
    lr: 
      base_lr: 5e-5
      pretrained: 5e-6  # the vit.
      depth_head: 5e-5
      pattern_prompt: 0
  
  schedulers:
    scheduler:
      - LinearLR:
          start_factor: 1e-3
          total_iters: [1000, steps]
      - CosineAnnealingLR:
          T_max: 
            - ${Train.n_epoches}
            - epoches
    milestones: [[1000, steps]]

  losses:
    l1:
      lambda: 1
      type: DepthL1Loss
    grad:
      lambda: 5
      type: DepthGradientLoss
      kwargs:
        gradient_operator: naive

Val:
  n_steps_per_vis: 100
  min_depth: ${Train.min_depth}
  max_depth: ${Model.max_depth}
  near: ${Train.min_depth}
  far: ${Model.max_depth}
  inp_size: [924, 518]

  fwd_kwargs:
    depth_type: ${Train.depth_type}
    lcn: False
    get_extra: False

  preprocess:
    - Transpose:  # must
        gray_single_channel: True
    # - RectifyPatterns:
    #     normalized_intri: False
    # - CeilPadpatch:
    #     patchsize: 14
    #     change_intri: False
    #     normalized_intri: False
    #     channel_last: False
    #     pad_depth: True
        
  metrics:
    RMSE:
      lambda: 1
      type: DepthRmseMetric
    MAE:
      lambda: 1
      type: DepthL1Loss
    REL:
      lambda: 1
      type: DepthRelMetric
    Delta_1.05:
      lambda: 1
      type: DepthDeltaThresholdMetric
      kwargs:
        threshold: 1.05
    Delta_1.10:
      lambda: 1
      type: DepthDeltaThresholdMetric
      kwargs:
        threshold: 1.10
    Delta_1.25:
      lambda: 1
      type: DepthDeltaThresholdMetric
      kwargs:
        threshold: 1.25
  