DATA_PATH: # PATH TO THE DATA_ROOT
RETURN_RIGHT_DISP: false
DATA_SPLIT: 'train'
DECOMPOSITION: false
CLEANED: True
FILE_FETCHER_TYPE: 'local'
GRAY: True
PARAMETERS: true
PATTERNNAME: null
NORMAL: false
MATERIALTYPE: false
match_lr: true